import type { Metadata } from "next";
import "./globals.css";
import { ConfirmationProvider } from "./components/molecules";

 
 
export const metadata: Metadata = {
  title: "Cashier",
  description: "Generated by eldir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ConfirmationProvider>{children}</ConfirmationProvider>
      </body>
    </html>
  );
}
