import type { Metadata } from "next";
import "./globals.css";
import { ConfirmationProvider } from "./components/molecules";
import StoreProvider from "@/app/store/StoreProvider";
import { LanguageProvider } from "./i18n";
import { ThemeProvider } from "./theme";
import { AuthInitializer } from "./components/atoms/AuthInitializer";

export const metadata: Metadata = {
  title: "Cashier",
  description: "Generated by eldir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <ThemeProvider>
            <LanguageProvider>
              <ConfirmationProvider>
                <AuthInitializer>{children}</AuthInitializer>
              </ConfirmationProvider>
            </LanguageProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
